service: growthhungry-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    CLERK_SECRET_KEY: ${env:CLERK_SECRET_KEY}

functions:
  api:
    handler: dist/index.handler
    events:
      - http:
          path: /
          method: any
          cors:
            origins:
              - "*" # Allows all origins (or set to "https://www.usefy.com" for more security)
            headers:
              - Content-Type
              - Authorization
              - X-Requested-With
              - Accept
      - http:
          path: "{proxy+}"
          method: any
          cors:
            origins:
              - "*" # Same as above
            headers:
              - Content-Type
              - Authorization
              - X-Requested-With
              - Accept
