name: Deploy Backend to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "./server/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        continue-on-error: true # fail workflow when tests fail

      - name: Install Serverless Framework v3
        run: npm install -g serverless@3.33.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Lambda
        run: serverless deploy --stage migration
        env:
          NODE_ENV: production
          # Clerk
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          # Stripe
          # STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          # AWS
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          # Email
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          # URLs
          API_URL: ${{ secrets.API_URL }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
